FROM rust as builder
WORKDIR /usr/src/block_chat
COPY . .
RUN cargo build --release

FROM rust:slim
WORKDIR /usr/src/block_chat
COPY ./input ./input
COPY --from=builder /usr/src/block_chat/target/release/helper /usr/local/bin/helper
CMD [ "helper" ]
