FROM rust as builder
WORKDIR /usr/src/block_chat
COPY . .
RUN cargo build --release

FROM rust:slim
WORKDIR /usr/src/block_chat
COPY --from=builder /usr/src/block_chat/target/release/daemon /usr/local/bin/daemon
CMD [ "daemon" ]
